# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IntegrateDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntegrateDemo
#  pod 'BESDK', :path => '../'
  pod 'BESDK', :git => 'https://github.com/belatoi/besdk-transport.git', :tag => 'v1.0.5'
#  pod 'BESDK', :git => 'https://github.com/belatoi/besdk-transport.git', :branch => 'development'

  target 'IntegrateDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntegrateDemoUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
#    if target.name == 'NKButton' || target.name == 'SwiftLocation'
#      target.build_configurations.each do |config|
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#      end
#    end
    
    if target.name == 'AFDateHelper' || target.name == 'SwiftLocation'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
