# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IntegrateDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntegrateDemo
#  pod 'BESDK', :path => '../'
  pod 'BESDK', :git => 'https://github.com/belatoi/besdk-transport.git', :tag => 'v1.0.8'
#  pod 'BESDK', :git => 'https://github.com/belatoi/besdk-transport.git', :branch => 'development'

  target 'IntegrateDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntegrateDemoUITests' do
    # Pods for testing
  end

end
